export const PAY_DONATION = 'PAY_DONATION';
export const PAY_DONATION_SUCCESS = 'PAY_DONATION_SUCCESS';
export const PAY_DONATION_ERROR = 'PAY_DONATION_ERROR';
export const GET_RECEIPT = 'GET_RECEIPT';
export const PAYMENT_SUCCESS_RECEIPT = 'PAYMENT_SUCCESS_RECEIPT';
